### ISSUE TITLE
使用Taro 命令的时候回出现错误Cannot find module '@tarojs/plugin-platform-weapp' from '/Users/boyad/code/udong/taro/Taro-Code-In-React-Native-main'

### ISSUE THREAD

**Issue by boyad-zl** [wuba/Taro-Code-In-React-Native#3]
在项目根目录中打开终端输入 taro build --help
`taro build --help   `

`
👽 Taro v3.2.10

/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/node_modules/resolve/lib/sync.js:81
    var err = new Error("Cannot find module '" + x + "' from '" + parent + "'");
              ^

Error: Cannot find module '@tarojs/plugin-platform-weapp' from '/Users/boyad/code/udong/taro/Taro-Code-In-React-Native-main'
    at Function.resolveSync [as sync] (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/node_modules/resolve/lib/sync.js:81:15)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/utils/index.js:46:31
    at Array.map (<anonymous>)
    at Object.resolvePresetsOrPlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/utils/index.js:45:30)
    at Kernel.resolvePlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:90:36)
    at Kernel.initPresetsAndPlugins (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:81:14)
    at Kernel.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:40:18)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:8:71
    at new Promise (<anonymous>) {
  code: 'MODULE_NOT_FOUND'
}`

**Comment by yechunxi** [comment]
这是一个rn的项目，包含原生的rn页面和taro的页面相结合的方案，所以Taro命令是不支持，多端开发的Demo,  参考https://github.com/wuba/Taro-Mortgage-Calculator
